# Distributions that don't use syslog-ng should do something 
# different here, but note that the log file path in asunder.conf
# is also mentioned in the Preferences UI.
#
install:
	cp asunder.conf /etc/rsyslog.d
uninstall:
	rm -f /etc/rsyslog.d/asunder.conf
